# Listener configuration
https:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"

# API specification
api:
  #Replace with respective autodiscovery id
  autodiscoveryID: ""
  
  
#DB config details
db:
  host: ""
  port: ""
  user: ""
  serviceName: "jdorcldv.netjiuwoz.vcnzgqox.oraclevcn.com"
  
  
#app name
app:
  name: "ntn-accounts-sf-jde-sync-sapi"  
  env: "PRODUCTION"  
     
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "simran.modi@prowesssoft.com"  
  

