# Listener configuration
https:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"


db:
  host: "129.147.16.38"
  port: "1521"
  svc: "jdeorcl.netuenazr.vcnzgqox.oraclevcn.com"
  query: "SELECT MAX(AXAN8) AS AXAN8 FROM PRODDTA.F4780 WHERE trim(AXDC) = :ID and  trim(AXXRTS) = 'SF'"
  #query: "SELECT AXDC FROM PRODDTA.F4780 WHERE trim(AXAN8) = :AN8 and  trim(AXXRTS) = 'SF'"
    
        
sf:
  authURL: "https://login.salesforce.com/services/Soap/u/56.0" 
                  
#ntn web service details
wsdl:
  path : "https://ntnpd.opc.oracleoutsourcing.com/PD920/SalesForceProcessManager?wsdl"
  service : "SalesForceProcessManagerService"
  port : "SalesForceProcessManagerPort"
  address : "https://ntnpd.opc.oracleoutsourcing.com/PD920/SalesForceProcessManager"
  username : "BIZSERVICE"
  
#Request Timeout config
http-request:
  timeout: "6000000"  

#app name
app:
  name: "ntn-accounts-sf-jde-sync-sapi"  
  env: "PROD"  
  
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"
  


