# Listener configuration
https:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"

# API specification
api:
  #Replace with respective autodiscovery id
  #autodiscoveryID: "19830835"
  
  
#DB config details
db:
  host: "129.147.16.140"
  port: "1521"
  user: "c_mulesoft"
  serviceName: "jdorcldv.netjiuwoz.vcnzgqox.oraclevcn.com"
  
  
#app name
application:
  name: ""    
  
  

