# Listener configuration
https:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/v1/*"


db:
  host: "129.147.16.139"
  port: "1521"
  svc: "jdorclpy.netjiuwoz.vcnzgqox.oraclevcn.com"
  query: "SELECT AXDC FROM CRPDTA.F4780 WHERE trim(AXAN8) = :AN8 and  trim(AXXRTS) = 'SF'"


#ntn-accounts-sync-papi client details
ntn:
  proc:
    clientId: "" 

    
        
sf:
  authURL: "https://test.salesforce.com/services/Soap/u/56.0" 
                  
#ntn web service details
wsdl:
  path : "wsdl/Accounts.wsdl"
  service : "SalesForceProcessManagerService"
  port : "SalesForceProcessManagerPort"
  address : "https://ntnpy.opc.oracleoutsourcing.com/PY920/SalesForceProcessManager"
  username : "BIZSERVICE"
  
#Request Timeout config
http-request:
  timeout: "6000000"  

#app name
app:
  name: "ntn-accounts-sf-jde-sync-sapi"  
  env: "UAT"  
  
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "simran.modi@prowesssoft.com"

