db:
  password: "![8M3rPy3SGjM=]"
  user: "![c6/KkkNKJ/o=]"
  


#ntn web service details
wsdl:
  password : "![5CxDaSFuTAw=]" 

  
smtp:
  user: "![hRt1ri9KnH7VngaJcayGZ0D8arLBERHy1f3i+Ca4XPI=]"
  password: "![BapbFMsL0srqwUVI3ICHLlxe4IERbHKP]"
  
    
sf:
  token: "![pxS/bMSXsKXRM/Ph2PWwFqE1Lk9fXlTzNNGx3zwfAz8=]"
  password: "![2YNZt1lm+MRm7qkhAuEumw==]"
  user: "![hRt1ri9KnH4qzOtJxnTIpRiC0yiHqDLpKpzaFPQu0vc=]"        