#%RAML 1.0 DataType
type: object
properties:
  id ?:
    type : string
    example: "001VC00000HKSKxYAP"
  nbcaMarket ? :
    type : string
    example : 30"
  region ?:
    type: string
    example: "29374"
  custTypeCode ?:
    type: string
    example: "29374"
  ntnSalesRep ? :
    type: string
    example: "29374"
  customerServiceCoordinatorCode ? :
    type: string
    example: "RN"
  mktRep ? :
    type: string
    example: "Wajax Industrial Components"
  engineer ? :
    type: string
    example: "DG"
  ntnMarketCode ? :
    type: string
    example: "342-55-6642"
  ntnCustomerGroup ? :
    type: string
    example: "2022-04-15"
  ntnGlobalMarket ? :
    type: string
    example: "48"
  shippingStreet ?:
    type: array
    example: [
    "1600 Bishop Ct.",
    "Corporate Office",
    "Suite 207",
    "Unit 1"
  ]
  shippingStateCode ? :
    type: string
    example: "NS"
  shippingPostalCode ? :
    type: string
    example: "Industrial OEM"
  alphaName ? :
    type: string
    example: "Received AG Pricing"
  jdeAddressNumber ? :
    type: string
    example: "Special Electric Motor Discount"
  billToNumber ? :
    type: string
    example: "Group A"
  parentNumber ? :
    type: string
    example: "MRO Schedule Name"
  ntnAdvPrcGrp ? :
    type: string
    example: "Industrial Authorized Dist."
  billingAddressType ? :
    type: string
    example: "Wajax Industrial Components LP"
  shippingCountryCode ? :
    type: string
    example: "Industrial OEM"
  shippingCity ? :
    type: string
    example: "Industrial Distributor"
  dunsNumber ? :
    type: string
    example: "Eastern Region"
  fax ? :
    type: string
    example: "(123)4567898"
  phone ? :
    type: string
    example: "Active"
  ntnCompanyName ? :
    type: string
    example: "NBCC"
  type ? :
    type: string
    example: "Wajax Industrial Components Billing Center"
  advPriceAG ? :
    type: string
    example: "555" 
  advPriceEMB ? :
    type: string
    example: "https://www.ntnconnect.com"
  advPriceUCP ? :
    type: string
    example: "1600 Easy Street Unit 201 Bay 3"  
