#%RAML 1.0 Library

 resourceTypes:
  CreateOnlyResourceType: !include /resourceTypes/create-only.raml
  ReadOnlyResourceType: !include /resourceTypes/read-only.raml
  UpdateOnlyResourceType: !include /resourceTypes/update-only.raml
  CreateupdateResourceType: !include /resourceTypes/create-update-only.raml